# Specify base Image
# <image-name>:<tag>
# if there's no tag, the latest will be downloaded.
FROM alpine

# Download additional required files
# RUN command

# Specify the command to be executed when the contianer starts
# can use only once in dockerfile.
CMD [ "echo", "hello" ]